version: '3'

services:
    eigen_service:
        build: .
        ports:
          - "3000:3000"
    fns:
        image: ieigen/fns:v4
        working_dir: '/app/release/services'
        command:
            - bash
            - -c
            - |
                source /opt/sgxsdk/environment
                ./fns
        ports:
            - '8082:8082'