version: '3'

services:
    proxy:
        build: ./proxy/
        ports:
          - "8443:8443"
        networks:
          - default
    eigen_service:
        build: .
        ports:
          - "3000:3000"
        networks:
          - default
    fns:
        image: ieigen/fns:v4
        working_dir: '/app/release/services'
        command:
          - bash
          - -c
          - |
            source /opt/sgxsdk/environment
            ./fns
        ports:
          - '8082:8082'
        environment:
          - IAS_SPID=replace_me
          - IAS_KEY=replace_me
          - RUST_LOG=debug
          - KMS_KEY_ID=replace_me
          - KMS_CLIENT_ID=replace_me
          - KMS_CLIENT_SK=replace_me
          - KMS_CLIENT_REGION=replace_me
        networks:
          - default

networks:
  default:
    driver: bridge
