name: CI
on:
  push:
    branches:
      - main
      - ci
  pull_request:

jobs:
  test:
    name: Test our project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn install --frozen-lockfile
      - name: Unit Tests
        run: yarn test
